'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _default18

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''loggedUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loggedUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DashboardLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DashboardLink As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CompanyManagementLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyManagementLink As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''InstrumentManagementLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InstrumentManagementLink As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''StaticDataLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StaticDataLink As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ExportPermitManagementLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportPermitManagementLink As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ImportPermitManagementLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImportPermitManagementLink As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FileManagerLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileManagerLink As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ReportingLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportingLink As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ExportDataLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportDataLink As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''HomePageTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePageTab As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LogoutAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogoutAdmin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SelectCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectCompany As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SelectQuarter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectQuarter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ShowPermitResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowPermitResult As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ExportPermitViewPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportPermitViewPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ProcessingData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProcessingData As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''NoRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoRecord As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ExportPermitGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportPermitGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''TabOverallContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabOverallContainer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''InspectionTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InspectionTab As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EndorsementTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndorsementTab As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''RecommentionTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecommentionTab As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ApprovalTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApprovalTab As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EntryAuthorizationTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntryAuthorizationTab As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ProductLoadingTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProductLoadingTab As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ContainerExitTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContainerExitTab As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''InspectionContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InspectionContent As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''InspectionOfficer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InspectionOfficer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''InspectionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InspectionStatus As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InspectionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InspectionDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''InspectionDateButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InspectionDateButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ProductDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProductDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PeriodCoverFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PeriodCoverFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PeriodCoverTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PeriodCoverTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''InspectionComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InspectionComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SaveInspection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveInspection As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RejectInspection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RejectInspection As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''EndorsementContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndorsementContent As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EndorsementPermitQuarter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndorsementPermitQuarter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EndorsementStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndorsementStatus As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''EndorsementDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndorsementDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EndorsementCalendarButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndorsementCalendarButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''EndorsedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndorsedBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EndorsementComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndorsementComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SaveEndorsement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveEndorsement As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelEndorsement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelEndorsement As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RecommendationContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecommendationContent As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''RecommendationPermitQuarter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecommendationPermitQuarter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RecommendationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecommendationStatus As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''RecommendationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecommendationDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RecommendationCalendarButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecommendationCalendarButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RecommendationBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecommendationBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RecommendationComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecommendationComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SaveRecommendation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveRecommendation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelRecommendation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelRecommendation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ApprovalContnet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApprovalContnet As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ApprovalPermitQuarter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApprovalPermitQuarter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ApprovalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApprovalStatus As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ApprovalDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApprovalDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ApprovalClandarButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApprovalClandarButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ApprovedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApprovedBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ApprovalComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApprovalComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SaveApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveApproval As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RejectApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RejectApproval As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''EntryAuthorization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntryAuthorization As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EntryPermitQuarter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntryPermitQuarter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EntryStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntryStatus As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''EntryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntryDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AuthorizeEntryCal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AuthorizeEntryCal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AuthorizedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AuthorizedBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AuthorizationComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AuthorizationComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AuthorizeEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AuthorizeEntry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RejectAuthorization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RejectAuthorization As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ProductLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProductLoading As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LoadingPermitQuarter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadingPermitQuarter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LoadingStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadingStatus As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LoadingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadingDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LoadedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadedBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LoaderComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoaderComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ApproveLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApproveLoading As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DenyLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DenyLoading As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ContainerExit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContainerExit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ExitPermitQuarter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExitPermitQuarter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ExitStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExitStatus As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ExitDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExitDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button7 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ExitBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExitBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ExitComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExitComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ApproveExit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApproveExit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DenyExit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DenyExit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ApplicationStatusText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApplicationStatusText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NonTerminalOperator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonTerminalOperator As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''TerminaOperator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TerminaOperator As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ApplicationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApplicationStatus As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CertificateOfIncorporation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CertificateOfIncorporation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MemorandumOfAssociation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MemorandumOfAssociation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CurrentProduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentProduction As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ConformityCertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConformityCertificate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BankReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankReference As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ClearanceCertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClearanceCertificate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ExportPermitApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportPermitApplication As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''EvidenceOfPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EvidenceOfPayment As Global.System.Web.UI.WebControls.Button
End Class
