'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _default42
    
    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''loggedUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loggedUser As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''DashboardLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DashboardLink As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''CompanyManagementLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyManagementLink As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''InstrumentManagementLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InstrumentManagementLink As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''StaticDataLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StaticDataLink As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ExportPermitManagementLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportPermitManagementLink As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ImportPermitManagementLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImportPermitManagementLink As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''FileManagerLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileManagerLink As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ReportingLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportingLink As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ExportDataLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportDataLink As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''HomePageTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePageTab As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LogoutAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogoutAdmin As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''SelectReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectReport As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ReportParameterLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportParameterLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SelectReportParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectReportParameter As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''FilterDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilterDateFrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FilterDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilterDateTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ShowReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowReport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GetDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetDate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ProcessingData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProcessingData As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''NoRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoRecord As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''NationwideReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NationwideReport As Global.Microsoft.Reporting.WebForms.ReportViewer
    
    '''<summary>
    '''StateReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StateReport As Global.Microsoft.Reporting.WebForms.ReportViewer
    
    '''<summary>
    '''YearlyReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YearlyReport As Global.Microsoft.Reporting.WebForms.ReportViewer
End Class
