'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _default29

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''HeaderPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeaderPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Account control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Account As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Logout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Logout As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RegistrationPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegistrationPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Registration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Registration As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ToolBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolBar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Inspection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Inspection As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''VerificationBill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VerificationBill As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Enforcement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Enforcement As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Instruments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Instruments As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DepositPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DepositPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''WelcomeMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WelcomeMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SlidePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlidePanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LoginPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UserType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Username As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LoginButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PasswordReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordReset As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PasswordResetPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordResetPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AccountEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SecurityQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecurityQuestion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SecurityAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecurityAnswer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NewPasswordLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NewPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ConfirmPasswordLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ConfirmPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ContinueReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContinueReset As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SearchAcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchAcount As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ResetMyPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResetMyPassword As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GoToLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoToLogin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RefreshNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefreshNews As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TitlePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitlePanel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''NewsTitle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewsTitle1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PreviewPane1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviewPane1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''NewsPreview1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewsPreview1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''A4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''TitlePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitlePanel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''NewsTitle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewsTitle2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PreviewPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviewPanel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''NewsPreview2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewsPreview2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''A3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''TitlePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitlePanel3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''NewsTitle3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewsTitle3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PreviewPanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviewPanel3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''NewsPreview3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewsPreview3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''A2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''TitlePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitlePanel4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''NewsTitle4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewsTitle4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PreviewPanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviewPanel4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''NewsPreview4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewsPreview4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''A1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
